# Generated by Django 4.2.4 on 2023-08-22 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_idservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
