# Generated by Django 4.2.4 on 2023-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='n_serie',
            field=models.BigIntegerField(default=1234567893),
        ),
        migrations.AddField(
            model_name='cliente',
            name='router',
            field=models.CharField(default='Mercusi', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[['A', 'A'], ['B', 'B'], ['S', 'S']], default='A', max_length=1),
        ),
    ]
