# Generated by Django 4.2.4 on 2023-09-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_n_serie_cliente_router_alter_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueda',
            name='id_deuda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
