# Generated by Django 4.2.4 on 2023-10-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_dueda_id_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientedeuda',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
